---
# This playbook is used to update ubuntu servers and if server needs to be restarted then schedule automatic restart at 3 AM next day.
- name: Update Ubuntu servers, check reboot status, and schedule restart if needed
  hosts: ubuntu_servers
  become: yes
  inventory: ../inventory/hosts.ini  # Update this path if you make any changes to inventory file location
  
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Perform package upgrade
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required
      ignore_errors: true  # Ignore error if file does not exist

    - name: Display reboot status
      debug:
        msg: "Server {{ inventory_hostname }} requires reboot."
      when: reboot_required.stat.exists

    - name: Schedule reboot using 'at' if required
      shell: echo "/sbin/shutdown -r now" | sudo /usr/bin/at 3am tomorrow
      when: reboot_required.stat.exists
      register: schedule_result
      ignore_errors: true

    - name: Retrieve 'at' queue
      shell: sudo /usr/bin/atq
      register: atq_output

    - debug:
        var: atq_output.stdout_lines
